version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest

  presentation:
    image: ${DOCKER_REGISTRY-}presentation
    build:
      context: .
      dockerfile: Presentation/Dockerfile

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Service.Api/Dockerfile
