version: '3.4'

services:
  mssql:   
    container_name: mssql
    environment:
        - SA_PASSWORD=Pass@word
        - ACCEPT_EULA=Y
    restart: unless-stopped 
    ports:
        - "1433:1433"
    networks:
      - local

  api:
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:ApplicationDbContext=Server=mssql,1433;Database=ApplicationDb;User Id=sa;Password=Pass@word;TrustServerCertificate=True;"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - 8600:80
    depends_on:
        - mssql
    networks:
      - local

  presentation:  
    container_name: presentation
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiUrl=http://api/"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - 8500:80
    depends_on:
        - mssql
        - api
    networks:
      - local
networks:
  local:
    driver: bridge